#######################################################################################################################
# 功能: 启动容器
#     1) mysql:               数据库服务
#     2) redis:               缓存服务
#     3) config-server:       配置中心
#     4) user:                用户服务
# 作者: 应卓
# 日期: 2016-08-31
#######################################################################################################################

mysql:
  image: mysql:5.5.49
  ports:
    - 13306:3306
  volumes:
    - /tmp:/tmp
    - /etc/timezone:/etc/timezone
    - /home/yingzhuo/projects/kuruma/volume/mysql/data:/var/lib/mysql
    - /home/yingzhuo/projects/kuruma/config/mysql/:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=root
    - MYSQL_USER=yingzhuo
    - MYSQL_PASSWORD=yingzhuo

config_server:
  image: yingzhuo/kuruma-config-server:latest
  ports:
    - 8888:8888
  volumes:
    - /tmp:/tmp
  environment:
    - SPRING_PROFILES_ACTIVE=cloud
  command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

user:
  image: yingzhuo/kuruma-user:latest
  ports:
    - 7777:7777
  volumes:
    - /tmp:/tmp
  environment:
    - SPRING_PROFILES_ACTIVE=cloud
  links:
      - mysql:mysql
      - config_server:configserver
  entrypoint: dockerize -wait tcp://mysql:3306 -timeout 60s
  entrypoint: dockerize -wait tcp://configserver:8888 -timeout 60s
  command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"